[package]
name = "hsoh/project-run"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
janitor = "howmanysmall/janitor@1.18.3"
profileservice = "surnautica/profileservice@1.0.0"
react = "jsdotlua/react@17.2.1"
react-roblox = "jsdotlua/react-roblox@17.2.1"
bytenet = "ffrostflame/bytenet@0.4.6"